name: "💡 Suggestion"
description: "Suggest a product or user experience improvement."
title: "[Suggestion]: "
labels: ["suggestion"]

body:
  - type: textarea
    attributes:
      label: Suggestion
      description: Describe your idea.
    validations:
      required: true